"""Write the release v2 attribution list and quality report.

    python scripts/v2_release_report.py                 # reads data/release/v2/, writes both files

Inputs are what `build_release_v2.py` produced, plus, when they exist, the
overlap agreement written by `v2_packet.py merge` and the sampled audit written
by `v2_audit_sample.py`. Decision: ADR-0030 sections 2, 4 and 5.

Both outputs are generated. Do not hand-edit them; change this script instead.
"""

from __future__ import annotations

import collections
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RELEASE = ROOT / "data" / "release" / "v2"
STAGING = ROOT / "data" / "staging"

# One line per source, in the order the attribution list should read them.
# The licence text is the record's own; this table only adds the human context
# a reader needs (what the source is, and what its terms require of us).
SOURCE_NOTES = {
    "RecipeNLG (Gathered)": (
        "RecipeNLG, `Gathered` subset only. Non-commercial research and educational use. "
        "Each recipe keeps the URL of the site it was gathered from."
    ),
    "Wikibooks Cookbook": (
        "Wikibooks Cookbook, CC BY-SA 4.0. Attribution and share-alike apply to the "
        "source text; our derived fields are listed separately below."
    ),
    "TheMealDB": "TheMealDB, used under its terms, which ask for attribution and a link.",
    "web-intake": (
        "Imported from the web during use (ADR-0032). Tier 1 records keep the source's "
        "step text; tier 2 records carry steps rewritten in our own words."
    ),
}


def read_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


def pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def attribution(recipes: list[dict], ingredients: list[dict]) -> str:
    by_dataset: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    for recipe in recipes:
        source = recipe.get("source") or {}
        by_dataset[source.get("dataset") or "unknown"][source.get("license") or "unstated"] += 1

    lines = [
        "# Release v2 attribution",
        "",
        "Generated by `scripts/v2_release_report.py`. Decision: `ADR-0030` section 2.",
        "",
        "This release is a **collection of separately licensed records**. It is not",
        "relicensed as a whole. Every recipe carries its own `source.license` and",
        "`source.source_url` in `recipes.jsonl`; this file summarises what is in there.",
        "Use is non-commercial.",
        "",
        "## Recipe sources",
        "",
        "| Source | Recipes | Licence as recorded |",
        "| --- | ---: | --- |",
    ]
    for dataset in sorted(by_dataset, key=lambda d: -sum(by_dataset[d].values())):
        for licence, count in by_dataset[dataset].most_common():
            lines += [f"| {dataset} | {count} | {licence} |"]
    lines += [""]
    for dataset in sorted(by_dataset, key=lambda d: -sum(by_dataset[d].values())):
        note = SOURCE_NOTES.get(dataset)
        if note:
            lines += [f"**{dataset}.** {note}", ""]

    with_url = sum(1 for r in recipes if (r.get("source") or {}).get("source_url"))
    lines += [
        f"Per-recipe source URLs: {with_url} of {len(recipes)} records carry one. "
        "The remainder come from a source that publishes no per-recipe URL; their dataset "
        "is named in `source.dataset`.",
        "",
        "## Ingredient nutrition and weights",
        "",
        "Ingredient nutrition per 100 g and unit weights were compiled for this release from",
        "public food-composition tables and manufacturer labels, and from reasoned estimates",
        "where no table covers the form recipes use. Every value records its basis and its",
        "sources in `ingredients.jsonl` under `forms.*.sources`. Most-cited sources:",
        "",
    ]
    hosts: collections.Counter = collections.Counter()
    for record in ingredients:
        for form in (record.get("forms") or {}).values():
            for source in form.get("sources") or []:
                url = source.get("url") or ""
                host = url.split("/")[2] if url.startswith("http") and len(url.split("/")) > 2 else None
                if host:
                    hosts[host] += 1
    for host, count in hosts.most_common(12):
        lines += [f"- {host} — cited {count} times"]
    if not hosts:
        lines += ["- (no ingredient sources recorded yet)"]
    lines += [
        "",
        "## What is ours",
        "",
        "The structured record — canonical ingredient identities, gram weights per line,",
        "per-serving nutrition, rule-derived allergens and dietary tags, course, cuisine,",
        "meal types, difficulty and times — was produced by this project and is not taken",
        "from any source above.",
        "",
    ]
    return "\n".join(lines)


def quality_report(summary: dict, manifest: dict, agreement: dict, audit: dict, recipes: list[dict]) -> str:
    counts = manifest.get("counts", {})
    coverage = summary.get("coverage", {})
    estimated = summary.get("estimated_share", {})
    lines = [
        "# Release v2 quality report",
        "",
        "Generated by `scripts/v2_release_report.py` from the build outputs in",
        "`data/release/v2/`. Decision: `ADR-0030` sections 4 and 5. Do not hand-edit.",
        "",
        f"Release `{summary.get('release_version', 'v2')}`, built {summary.get('created_at', 'unknown')}.",
        "",
        "## Size",
        "",
        "| | Count |",
        "| --- | ---: |",
        f"| Released recipes | {coverage.get('released_recipes', 0)} |",
        f"| Distinct ingredients used | {coverage.get('released_ingredients', 0)} |",
        f"| Candidates entering enrichment | {coverage.get('enrichment_set', 0)} |",
        f"| Built before the quota cut | {counts.get('built_before_quota', 0)} |",
        "",
        "Every released recipe carries prep, cook and passive minutes, servings, course,",
        "cuisine, meal types, difficulty, per-serving nutrition, and a gram weight for every",
        "ingredient line. A candidate missing any of those is not in the release; the reasons",
        "are below.",
        "",
        "## Where the values came from",
        "",
        "A field is *stated* when the source gave it and *estimated* when enrichment supplied",
        "it with a recorded basis. The three are counted separately because they fail for",
        "different reasons.",
        "",
        "| Field | Estimated share |",
        "| --- | ---: |",
        f"| Servings | {pct(estimated.get('servings', 0))} |",
        f"| Times | {pct(estimated.get('times', 0))} |",
        f"| Ingredient line amounts | {pct(estimated.get('ingredient_amounts', 0))} |",
        "",
    ]

    lines += ["## Cuisine", "", "| Cuisine | Recipes |", "| --- | ---: |"]
    for cuisine, count in (summary.get("by_cuisine") or {}).items():
        lines += [f"| {cuisine} | {count} |"]
    lines += ["", "## Course", "", "| Course | Recipes |", "| --- | ---: |"]
    for course, count in (summary.get("by_course") or {}).items():
        lines += [f"| {course} | {count} |"]

    dropped = summary.get("dropped_by_reason") or {}
    lines += [
        "",
        "## What was dropped, and why",
        "",
        f"{sum(dropped.values())} candidates did not reach the release.",
        "",
        "| Reason | Candidates |",
        "| --- | ---: |",
    ]
    for reason, count in dropped.items():
        lines += [f"| {reason} | {count} |"]
    lines += ["", "The full list with titles is in `dropped.jsonl`.", ""]
    unbucketed = counts.get("unbucketed_cuisine")
    if unbucketed:
        lines += [
            f"A further {unbucketed} built recipes carry a cuisine no quota bucket claims "
            "(`international`) and are not released. A dish with a recognisable origin should "
            "carry that origin instead; `international` is for a dish that genuinely has none.",
            "",
        ]

    lines += ["## Spread of each producer's answers", ""]
    lines += [
        "A producer that fills the same value into almost every record has not read the",
        "sources, whatever the value is. For each producer this is the share of its released",
        "recipes sitting on its own single most common value for that field.",
        "",
        "| Producer | Recipes | prep | cook | passive | course | difficulty |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    by_producer: dict[str, list[dict]] = {}
    for recipe in recipes:
        by_producer.setdefault((recipe.get("enrichment") or {}).get("by") or "unknown", []).append(recipe)
    for producer, rows in sorted(by_producer.items(), key=lambda kv: -len(kv[1])):
        shares = []
        for field in ("prep_minutes", "cook_minutes", "passive_minutes", "course", "difficulty"):
            top = collections.Counter(r.get(field) for r in rows).most_common(1)[0][1]
            shares.append(pct(top / len(rows)))
        lines += [f"| {producer} | {len(rows)} | " + " | ".join(shares) + " |"]
    lines += [""]

    lines += ["## Agreement between producers", ""]
    if agreement:
        lines += [
            "About 3% of items were enriched twice, by different producers, to measure",
            "agreement. This is a consistency measure, not an accuracy measure: two producers",
            "can agree and both be wrong.",
            "",
        ]
        for kind, report in agreement.items():
            pairs = report.get("pairs", 0)
            lines += [f"**{kind}** — {pairs} double-enriched items.", ""]
            if pairs:
                lines += ["| Field | Agreement |", "| --- | ---: |"]
                for field, value in report.items():
                    if field != "pairs":
                        lines += [f"| {field} | {pct(value)} |"]
                lines += [""]
    else:
        lines += [
            "Not yet measured. Run `python scripts/v2_packet.py merge`, which writes",
            "`data/staging/v2_agreement.json`, then regenerate this report.",
            "",
        ]

    lines += ["## Sampled audit", ""]
    if audit:
        lines += [
            f"A random sample drawn with seed {audit.get('seed')} was re-checked by hand"
            f" on {audit.get('audited_at', 'an unrecorded date')}.",
            "",
            "| Kind | Sampled | Checks made | Accepted | Corrected |",
            "| --- | ---: | ---: | ---: | ---: |",
        ]
        for kind, result in (audit.get("results") or {}).items():
            lines += [
                f"| {kind} | {result.get('sampled', 0)} | {result.get('checks', 0)} | "
                f"{result.get('accepted', 0)} | {result.get('corrected', 0)} |"
            ]
        lines += [""]
        for note in audit.get("findings") or []:
            lines += [f"- {note}"]
        lines += [""]
    else:
        lines += [
            "Not yet run. `scripts/v2_audit_sample.py` draws the sample and records the",
            "verdicts; this section fills in from its output.",
            "",
        ]

    pending = summary.get("allergen_rules_pending_human")
    if pending is not None:
        lines += [
            "## Allergen rules",
            "",
            "Allergen labels are derived only from the rule table (`ADR-0024` section 3); an",
            "AI opinion is recorded to find disagreements and is never applied. An ingredient",
            "whose status is unknown is excluded by an allergen constraint, never admitted.",
            "",
            f"Rules still awaiting human confirmation: {pending}.",
            "",
        ]

    if recipes:
        energies = sorted(r["nutrition"]["energy_kcal"] for r in recipes if r.get("nutrition"))
        if energies:
            lines += [
                "## Nutrition sanity",
                "",
                f"Per-serving energy across the release: median {energies[len(energies) // 2]:.0f} kcal, "
                f"10th percentile {energies[len(energies) // 10]:.0f} kcal, "
                f"90th percentile {energies[len(energies) * 9 // 10]:.0f} kcal.",
                "",
                "A median far from roughly 300-700 kcal for a serving, or a long tail at either",
                "end, points at a gram-weight or servings problem rather than at unusual food.",
                "",
            ]
    return "\n".join(lines)


def main() -> int:
    recipes = read_jsonl(RELEASE / "recipes.jsonl")
    ingredients = read_jsonl(RELEASE / "ingredients.jsonl")
    summary = read_json(RELEASE / "quality_summary.json")
    manifest = read_json(RELEASE / "release_manifest.json")
    if not summary:
        raise SystemExit(f"no build output in {RELEASE}; run scripts/build_release_v2.py first")
    agreement = read_json(STAGING / "v2_agreement.json")
    audit = read_json(ROOT / "docs" / "v2-sampled-audit.json")

    (RELEASE / "ATTRIBUTION.md").write_text(attribution(recipes, ingredients), encoding="utf-8", newline="\n")
    (RELEASE / "quality_report.md").write_text(
        quality_report(summary, manifest, agreement, audit, recipes), encoding="utf-8", newline="\n"
    )
    print(f"wrote {RELEASE / 'ATTRIBUTION.md'}")
    print(f"wrote {RELEASE / 'quality_report.md'}")
    if not agreement:
        print("note: no agreement data yet (run v2_packet.py merge)")
    if not audit:
        print("note: no sampled audit yet (run v2_audit_sample.py)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
