"""Paired statistics over the recorded v2-multidish held-out runs (ADR-0028's open item).

    python scripts/paired_multidish.py

Reads only result files already written (`docs/evaluation/v2-multidish/heldout/latest.json`, run 4, and the
three further live passes `live-pass-v2-1..3.json`); it runs no arm and reads no episode. Writes
`docs/evaluation/v2-multidish/heldout/paired.md`.

Two analyses, both fixed before looking at their numbers:

1. Run 4, exact McNemar per comparison: the two-sided binomial test on the episodes where exactly one of
   the two arms succeeds. Six comparisons, each isolating one factor; p-values also Holm-adjusted across
   the six.
2. The live arms over four passes: per episode, the share of passes that succeeded. A and D are compared
   by an exact sign test over the episodes whose shares differ, so pass-to-pass noise within an arm is
   not read as a difference between arms.

The held-out set has been looked at four times (see findings.md); these numbers describe those runs, they
are not fresh evidence.
"""

import json
from collections import defaultdict
from math import comb
from pathlib import Path

HELDOUT = Path("docs/evaluation/v2-multidish/heldout")
RUN4 = HELDOUT / "latest.json"
LIVE_PASSES = [RUN4, *(HELDOUT / f"live-pass-v2-{n}.json" for n in (1, 2, 3))]
OUT = HELDOUT / "paired.md"

# (arm, arm, what the pair isolates)
COMPARISONS = [
    ("A", "C", "understanding: live model vs rule parser, same meal beam"),
    ("B", "A", "solver: CP-SAT vs meal beam, same live understanding"),
    ("A", "D", "who plans: meal beam vs the model itself, same live model"),
    ("O1", "A", "the gap to the bound: gold vs live understanding, same beam"),
    ("C", "E", "planner under the rule parser: meal beam vs strong rules"),
    ("E", "F", "baselines: strong rules vs greedy floor"),
]


def outcomes(path: Path) -> dict[str, dict[str, bool]]:
    """arm -> episode -> strict success."""
    table: dict[str, dict[str, bool]] = defaultdict(dict)
    for row in json.loads(path.read_text(encoding="utf-8"))["episodes"]:
        table[row["arm"]][row["episode_id"]] = bool(row["strict_success"])
    return table


def exact_two_sided(k: int, n: int) -> float:
    """Two-sided exact binomial p for k successes in n at p = 1/2 (McNemar and the sign test)."""
    if n == 0:
        return 1.0
    tail = sum(comb(n, i) for i in range(min(k, n - k) + 1)) / 2**n
    return min(1.0, 2 * tail)


def holm(pvalues: list[float]) -> list[float]:
    order = sorted(range(len(pvalues)), key=lambda i: pvalues[i])
    adjusted, running = [0.0] * len(pvalues), 0.0
    for rank, i in enumerate(order):
        running = max(running, min(1.0, (len(pvalues) - rank) * pvalues[i]))
        adjusted[i] = running
    return adjusted


def main() -> None:
    # The two helpers, checked against values worked by hand.
    assert exact_two_sided(0, 21) == 2 / 2**21 and exact_two_sided(1, 2) == 1.0
    assert holm([0.01, 0.04, 0.03]) == [0.03, 0.06, 0.06]
    run4 = outcomes(RUN4)
    episodes = sorted(next(iter(run4.values())))
    lines = [
        "# Paired statistics over the recorded held-out runs",
        "",
        "Generated by `scripts/paired_multidish.py` from result files already written; no arm was run and no",
        "episode read. The held-out set has been looked at four times (`findings.md`): these numbers describe",
        "those runs and are not fresh evidence.",
        "",
        f"## Run 4: exact McNemar, {len(episodes)} paired episodes",
        "",
        "`b` = episodes only the first arm passes, `c` = only the second. The test uses only those.",
        "",
        "| Comparison | Isolates | First | Second | b | c | p (exact) | p (Holm, 6) |",
        "|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    rows, pvalues = [], []
    for first, second, isolates in COMPARISONS:
        a, b = run4[first], run4[second]
        only_first = sum(a[e] and not b[e] for e in episodes)
        only_second = sum(b[e] and not a[e] for e in episodes)
        p = exact_two_sided(only_first, only_first + only_second)
        rows.append((first, second, isolates, sum(a.values()), sum(b.values()), only_first, only_second, p))
        pvalues.append(p)
    for (first, second, isolates, sa, sb, only_first, only_second, p), adjusted in zip(
        rows, holm(pvalues), strict=True
    ):
        lines.append(
            f"| {first} vs {second} | {isolates} | {sa}/{len(episodes)} | {sb}/{len(episodes)} "
            f"| {only_first} | {only_second} | {p:.3g} | {adjusted:.3g} |"
        )

    passes = [outcomes(path) for path in LIVE_PASSES]
    shares = {arm: {e: sum(p[arm][e] for p in passes) / len(passes) for e in episodes} for arm in ("A", "B", "D")}
    lines += [
        "",
        f"## Live arms over {len(passes)} passes",
        "",
        "Per episode, the share of passes that succeeded. `always` and `never` count episodes at 4/4 and 0/4.",
        "",
        "| Arm | mean share | always | sometimes | never |",
        "|---|---:|---:|---:|---:|",
    ]
    for arm, share in shares.items():
        values = list(share.values())
        lines.append(
            f"| {arm} | {sum(values) / len(values):.2f} | {sum(v == 1 for v in values)} "
            f"| {sum(0 < v < 1 for v in values)} | {sum(v == 0 for v in values)} |"
        )
    higher = sum(shares["A"][e] > shares["D"][e] for e in episodes)
    lower = sum(shares["A"][e] < shares["D"][e] for e in episodes)
    tied_ab = sum(shares["A"][e] == shares["B"][e] for e in episodes)
    lines += [
        "",
        f"A against D, sign test over episodes whose shares differ: A higher on {higher}, D higher on {lower}, "
        f"p = {exact_two_sided(higher, higher + lower):.3g}.",
        f"A and B have the same share on {tied_ab} of {len(episodes)} episodes: they share one understanding "
        "call per episode, so they are not independent evidence of each other.",
        "",
        "## Reading",
        "",
        "- With 40 episodes the protocol treats paired differences under about 20 points as noise (section 7);",
        "  the exact tests above say the same thing per comparison instead of by rule of thumb.",
        "- A McNemar p-value speaks to these 40 episodes and these runs; the set was used to decide two fixes",
        "  (runs 2 and 4), so a small p here is not a pre-registered result.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
